### ISSUE TITLE
Awesome Bar

### ISSUE THREAD

**Issue by tjbrn** [kosorin/awesome-rice#1]
Hi, first, congrats for the well done project!

I'm trying to use the bar on my awesme config, how can I import only the bar to my config?

![image](https://user-images.githubusercontent.com/10359351/235355967-1a0f2a76-dac3-4f39-9fc0-8c452eed0bf2.png)

**Comment by kosorin** [comment]
It's not that easy to import only the bar. It requires a lot of dependencies, so you basically need the whole config. I may be able to help you with a specific task.
