### ISSUE TITLE
Make first window take all the space

### ISSUE THREAD

**Issue by tuxdotrs** [kosorin/awesome-rice#11]
Hey, The first window that get's spawn is in the middle of the screen. I would like it to take all the space available. Can you guide me a little bit how can I do that. I'm currently learning AwesomeWM API's so not sure where to look first.

**Comment by kosorin** [comment]
Hi, remove the line with `master_fill_policy`. You may also want to set `gap_single_client = true`.

https://github.com/kosorin/awesome-rice/blob/5fa785d89cf455c5021deefa28b3f314fe0ba86a/rice/tags.lua#L23C1-L29C1

**Comment by tuxdotrs** [comment]
Awesome Thanks! Can we connect on discord if it's okay? Looking for people with similar interests.

**Comment by kosorin** [comment]
You can join the (non official) awesome wm discord community: https://discord.gg/BPat4F87dg
