### ISSUE TITLE
Wallpaper Menu

### ISSUE THREAD

**Issue by resslr** [kosorin/awesome-rice#5]
How do I enable/install the "feature flag" wallpaper_menu + Do you have a discord for faster contact?

**Comment by resslr** [comment]
+ What should I name my backgrounds

**Comment by resslr** [comment]
+ and last but not least how do I set my weather location, tysm

**Comment by resslr** [comment]
@kosorin

**Comment by resslr** [comment]
Also @kosorin I have an issue with notifications not showing

**Comment by kosorin** [comment]
The wallpaper context menu is just a very simple wallpaper manager. It uses `feh` and its `.fehbg` files. It searches the wallpaper directory for`.fehbg.<name>` files. When selected, the file replaces `.fehbg` in your home directory and runs `feh` to refresh your background image.

**Comment by resslr** [comment]
So if I have a file called ~/Wallpapers(MySetDir)/.fehbg.1 it would load?

**Comment by resslr** [comment]
> @kosorin The wallpaper context menu is just a very simple wallpaper manager. It uses `feh` and its `.fehbg` files. It searches the wallpaper directory for`.fehbg.<name>` files. When selected, the file replaces `.fehbg` in your home directory and runs `feh` to refresh your background image.

So is it a name.fehbg or .fehbg.name file?

**Comment by kosorin** [comment]
`.fehbg` in home dir, `.fehbg.name` in wallpaper dir

**Comment by resslr** [comment]
Alright, and as for the menu, it is referring to the config? + How to set weather location?

> `.fehbg` in home dir, `.fehbg.name` in wallpaper dir

also I appreciate all the help

**Comment by resslr** [comment]
Ty found it out
