### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by resslr** [kosorin/awesome-rice#9]
Hey can I get your discord so we can talk further, mostly something about the readmes and more functionality I can add :D

**Comment by kosorin** [comment]
https://discord.gg/xNkBzE6f

**Comment by resslr** [comment]
> https://discord.gg/xNkBzE6f

Do you want to keep this open so ppl can find or?

**Comment by tuxdotrs** [comment]
> https://discord.gg/xNkBzE6f

Hey can I get your discord as well? The current link is expired.

**Comment by kosorin** [comment]
You can join the (non official) awesome wm discord community: https://discord.gg/BPat4F87dg
